### ISSUE TITLE
[1.7.10] NPE when trade slot 2 is not null, but buying2 is not

### ISSUE THREAD

**Issue by Whimsyturtle** [DoubleDoorDevelopment/InsiderTrading#4]
I Removed Some OP Villager Trades, and Now When I Use Auto-Spawners from Draconic Evolution to Spawn Villagers, If a Villager Spawns with My "Removed Trade", it Will Cause the Save File to be In-Accessable, Since it Will Continually Crash when Logged into.

Crash Report (From latest.log):
[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
**Caused by: java.lang.NullPointerException
    at net.doubledoordev.insidertrading.util.TradeWrapper.matches(TradeWrapper.java:25) ~[TradeWrapper.class:?]
    at net.doubledoordev.insidertrading.util.TradeManipulation.apply(TradeManipulation.java:33) ~[TradeManipulation.class:?]
    at net.doubledoordev.insidertrading.InsiderTrading.handle(InsiderTrading.java:120) ~[InsiderTrading.class:?]
    at net.doubledoordev.insidertrading.asm.Hooks.manipulate(Hooks.java:23) ~[Hooks.class:?]**
    at net.minecraft.entity.passive.EntityVillager.func_70950_c(EntityVillager.java:543) ~[yv.class:?]
    at net.minecraft.entity.passive.EntityVillager.func_70934_b(EntityVillager.java:401) ~[yv.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71030_a(EntityPlayerMP.java:716) ~[mw.class:?]
    at net.minecraft.entity.passive.EntityVillager.func_70085_c(EntityVillager.java:188) ~[yv.class:?]
    at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032) ~[sw.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126) ~[yz.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810) ~[nh.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    ... 5 more

^ Parts of Interest Highlighted in Bold.

I Think You Should Not Use Null to Remove Villager Trades, Instead Replace them with minecraft:air Or Some Other Nonnull Object.

**Comment by dries007** [comment]
I'm sorry its taking so long to reply, it will get fixed.

**Comment by Whimsyturtle** [comment]
Is it fixed yet? (P.s. Sorry for the late reply as well.)

**Comment by dries007** [comment]
No, sorry. I'll try to have a poke at it tomorrow.

Op 25 feb. 2017 4:26 p.m. schreef "Wealthyturtle" <notifications@github.com

**Comment by dries007** [comment]
Can you please upload your config json file? I think it may be corrupt.

**Comment by dries007** [comment]
For the record: There are no recipes being nulled. This issues only happened when there was a remove filter with no second slot specified, that matched the first slot of a recipe with 2 slots.
There is only 2 such possible recipes in 1.7.10 according to the MC wiki, which is why it never happened during testing I'm guessing.

**Comment by Whimsyturtle** [comment]
Sorry for the late reply.

JSON File (Renamed to .txt due to Github being fussy about File Extensions):
[InsiderTrading.txt](https://github.com/DoubleDoorDevelopment/InsiderTrading/files/836268/InsiderTrading.txt)
